// AUTO-GENERATED by scripts/fetch-visa-bulletin.mjs — do not edit by hand.
// BAR-802 row 37: DOS Visa Bulletin (Final Action Dates). Family-Sponsored first,
// then Employment-Based. No Diversity (DV). Re-run the script to refresh monthly.

export interface VisaBulletinRow {
  /** Preference category code as published, e.g. "F2A" or "Other Workers". */
  category: string;
  /** Spanish label for the category. */
  categoryEs: string;
  /** Final Action Date per chargeability area ("C" = current, "U" = unavailable). */
  dates: {
    allAreas: string;
    china: string;
    india: string;
    mexico: string;
    philippines: string;
  };
}

export interface VisaBulletinData {
  /** Bulletin month, English, e.g. "June 2026". */
  monthLabel: string;
  /** Bulletin month, Spanish, e.g. "junio de 2026". */
  monthLabelEs: string;
  /** Source page on travel.state.gov. */
  sourceUrl: string;
  /** ISO date this data was imported. */
  fetchedAt: string;
  familyBased: VisaBulletinRow[];
  employmentBased: VisaBulletinRow[];
}

export const VISA_BULLETIN: VisaBulletinData = {
  "monthLabel": "June 2026",
  "monthLabelEs": "junio de 2026",
  "sourceUrl": "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin/2026/visa-bulletin-for-june-2026.html",
  "fetchedAt": "2026-06-24",
  "familyBased": [
    {
      "category": "F1",
      "dates": {
        "allAreas": "01SEP17",
        "china": "01SEP17",
        "india": "01SEP17",
        "mexico": "08NOV07",
        "philippines": "01MAY13"
      },
      "categoryEs": "F1 — Hijos(as) solteros(as) de ciudadanos estadounidenses"
    },
    {
      "category": "F2A",
      "dates": {
        "allAreas": "01JAN25",
        "china": "01JAN25",
        "india": "01JAN25",
        "mexico": "01JAN24",
        "philippines": "01JAN25"
      },
      "categoryEs": "F2A — Cónyuges e hijos(as) menores de residentes permanentes"
    },
    {
      "category": "F2B",
      "dates": {
        "allAreas": "22SEP17",
        "china": "22SEP17",
        "india": "22SEP17",
        "mexico": "15FEB09",
        "philippines": "08APR13"
      },
      "categoryEs": "F2B — Hijos(as) solteros(as) (21+) de residentes permanentes"
    },
    {
      "category": "F3",
      "dates": {
        "allAreas": "15FEB12",
        "china": "15FEB12",
        "india": "15FEB12",
        "mexico": "01MAY01",
        "philippines": "22NOV05"
      },
      "categoryEs": "F3 — Hijos(as) casados(as) de ciudadanos estadounidenses"
    },
    {
      "category": "F4",
      "dates": {
        "allAreas": "08NOV08",
        "china": "08NOV08",
        "india": "01NOV06",
        "mexico": "08APR01",
        "philippines": "15JUL07"
      },
      "categoryEs": "F4 — Hermanos(as) de ciudadanos estadounidenses"
    }
  ],
  "employmentBased": [
    {
      "category": "1st",
      "dates": {
        "allAreas": "C",
        "china": "01APR23",
        "india": "15DEC22",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "1ª — Trabajadores prioritarios"
    },
    {
      "category": "2nd",
      "dates": {
        "allAreas": "C",
        "china": "01SEP21",
        "india": "01SEP13",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "2ª — Profesionales con títulos avanzados / aptitud excepcional"
    },
    {
      "category": "3rd",
      "dates": {
        "allAreas": "01JUN24",
        "china": "01AUG21",
        "india": "15DEC13",
        "mexico": "01JUN24",
        "philippines": "01AUG23"
      },
      "categoryEs": "3ª — Trabajadores calificados y profesionales"
    },
    {
      "category": "Other Workers",
      "dates": {
        "allAreas": "01FEB22",
        "china": "01APR19",
        "india": "15DEC13",
        "mexico": "01FEB22",
        "philippines": "01NOV21"
      },
      "categoryEs": "Otros Trabajadores"
    },
    {
      "category": "4th",
      "dates": {
        "allAreas": "15JUL22",
        "china": "15JUL22",
        "india": "15JUL22",
        "mexico": "15JUL22",
        "philippines": "15JUL22"
      },
      "categoryEs": "4ª — Ciertos inmigrantes especiales"
    },
    {
      "category": "Certain Religious Workers",
      "dates": {
        "allAreas": "15JUL22",
        "china": "15JUL22",
        "india": "15JUL22",
        "mexico": "15JUL22",
        "philippines": "15JUL22"
      },
      "categoryEs": "Ciertos Trabajadores Religiosos"
    },
    {
      "category": "5th Unreserved (including C5, T5, I5, R5, NU, RU)",
      "dates": {
        "allAreas": "C",
        "china": "22SEP16",
        "india": "01MAY22",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "5th Unreserved (including C5, T5, I5, R5, NU, RU)"
    },
    {
      "category": "5th Set Aside: Rural (20%, including NR, RR)",
      "dates": {
        "allAreas": "C",
        "china": "C",
        "india": "C",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "5th Set Aside: Rural (20%, including NR, RR)"
    },
    {
      "category": "5th Set Aside: High Unemployment (10%, including NH, RH)",
      "dates": {
        "allAreas": "C",
        "china": "C",
        "india": "C",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "5th Set Aside: High Unemployment (10%, including NH, RH)"
    },
    {
      "category": "5th Set Aside: Infrastructure (2%, including RI)",
      "dates": {
        "allAreas": "C",
        "china": "C",
        "india": "C",
        "mexico": "C",
        "philippines": "C"
      },
      "categoryEs": "5th Set Aside: Infrastructure (2%, including RI)"
    }
  ]
};
